// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oynesunhhllhqbpgpocv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95bmVzdW5oaGxsaHFicGdwb2N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3Nzk3NTUsImV4cCI6MjA2MTM1NTc1NX0._vYZmruhnqTuR7p_wvJVg84JIDUkVDYThiv9FHef57M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);